name: Release

on:
  push:
    tags:
      - v*

jobs:
    build-jar:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3


        - name: Setup Java
          uses: actions/setup-java@v4
          with:
            distribution: "temurin"
            java-version: 17

        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v3

        - name: Build
          run: ./gradlew shadowjar

        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            name: sinon.jar
            path: ./build/libs/sinon.jar

    publish:
      needs: [build-jar]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Download Linux
          uses: actions/download-artifact@v2
          with:
            name: sinon.jar
            path: ./files

        - name: Create Release
          uses: softprops/action-gh-release@v1
          with:
              files: |
                ./files/sinon.jar
              tag_name: ${{ github.ref }}
              body: |
                # Changelog
                ${{ github.event.release.body }}
                
                This is an automated draft release.
              draft: true
              prerelease: ${{ contains(github.ref, 'pre') || contains(github.ref, 'prerelease') }}
